In [7]:
import numpy as np
import pandas as pd
import xgboost as xgb

In [8]:
test_data = pd.read_csv('data/test_data_annot_example.csv')

In [9]:
test_data.head(n=10)

,chr,start,end,seq1,seq2,label,Median_sequence,GC,length,DNase,ATAC,H3K27ac,H3K4me3,DeepSpCas9_harmony,DeepCRISPR_harmony,CRISPRedict_harmony,Ruleset2_harmony,hyena_score
0,chr2,47403275,47403358,CCCTGGGTCTTGAACACCTCCCGGGCGGCC,CACTGTGGTGGTCGGCTTCTCCGGCATGCC,1,AAGCCGACCACCACAGTGCGCCTTTTCGACCGGGGCGACTTCTATA...,0.698795,83,19235.007473,11772.715284,85207.366522,53401.128708,4.777108,0.737907,3.601607,3.152460,-4.765686
1,chr2,47403275,47403358,CCCTGGGTCTTGAACACCTCCCGGGCGGCC,CACTGTGGTGGTCGGCTTCTCCGGCATGCC,1,AAGCCGACCACCACAGTGCGCCTTTTCGACCGGGGCGACTTCTATA...,0.698795,83,19235.007473,11772.715284,85207.366522,53401.128708,4.777108,0.737907,3.601607,3.152460,-4.765686
2,chr2,47570926,47571032,GCTGAGAAAGGAGCGCTTCCCCGGACTCGG,GGGGAGGGGTGAGTAGGGACAGGAGGGAGG,1,AAGCGCTCCTTTCTCAGCTCCAGCCGAAGAGCCGCCCGGCAGGGAG...,0.707547,106,16340.852330,16160.568125,0.000000,1052.344573,4.497032,0.724893,4.045393,3.430275,-4.626955
3,chr19,55115682,55115807,CCAGATAAGGAATCTGCCTAACAGGAGGTG,GGTTAATGTGGCTCTGGTTCTGGGTACTTT,0,GTGGGGGTTAGACCCAATATCAGGAGACTAGGAAGGAGGAGGCCTA...,0.552000,125,27098.822651,2287.840218,15016.699544,15744.721939,4.485945,0.726060,4.122885,3.626292,-5.673857
4,chr2,46500201,46500349,CACGTATCCTTTGAGTAACTTGCCAACTTG,GAGAGAGCAGGTTTGAATGTCCGGACAGTC,1,TTGGGGTGATGAAAACGCACTCCCCTCCTCCCGCCGCCGCTGGGTC...,0.594595,148,68092.121802,34060.248133,20401.045373,15380.605068,4.442847,0.722944,2.277320,4.101232,-3.303635
5,chrX,134373300,134373428,ACGCTCTGTGGGTCGTGTGCGTGCGAGGGG,TGCAGGAGAGAAGCGCCAATGAGGGTAAAG,1,GGGGGCGACGTAAGGGCGCTCCGCGAGCCCGTCTCTCCTCGAATGA...,0.609375,128,26297.998099,27743.968226,22513.637718,42985.632368,4.439551,0.723487,3.184594,3.250043,-3.546132
6,chr19,55115682,55115807,GGTTAATGTGGCTCTGGTTCTGGGTACTTT,CCAGATAAGGAATCTGCCTAACAGGAGGTG,0,GTGGGGGTTAGACCCAATATCAGGAGACTAGGAAGGAGGAGGCCTA...,0.552000,125,27098.822651,2287.840218,15016.699544,15744.721939,4.435765,0.726060,4.046481,3.648391,-5.673857
7,chr19,55115682,55115807,GGTTAATGTGGCTCTGGTTCTGGGTACTTT,CCAGATAAGGAATCTGCCTAACAGGAGGTG,0,GTGGGGGTTAGACCCAATATCAGGAGACTAGGAAGGAGGAGGCCTA...,0.552000,125,27098.822651,2287.840218,15016.699544,15744.721939,4.435765,0.726060,4.046481,3.648391,-5.673857
8,chr3,37860431,37860556,CGGGCATGTCCAGCTCTTCTGTGGCTTCCA,CACGAATCAGGAGGGCCTGGGAGGGCCTAC,1,AAGAGCTGGACATGCCCGCAAGGCCTGAAGTGCGCGCGCAACCTAG...,0.688000,125,95432.586338,31428.409102,3101.870986,700.906563,4.407197,0.719852,4.281820,4.121949,-2.852188
9,chr7,6008939,6008994,GAGCTGAGAGCTCGAGGTGAGCGGGGCTCG,CCCATTTCCAGGGAGGTTGGAATGCCGTGG,1,TGGGTCTCAAAGAGGGCGCGCGAGAGGGGACACCGGAAGACTGCGA...,0.690909,55,12654.482193,10274.584539,60540.166831,32344.927701,4.381765,0.720598,4.038908,3.579092,-6.229518

In [10]:
xgb_model = xgb.XGBRegressor()
xgb_model.load_model('./xgboost_model.model')

test_data = test_data.fillna(0.0)

features = ['DNase','ATAC','H3K27ac','H3K4me3','GC','length',
             'DeepSpCas9_harmony','DeepCRISPR_harmony','Ruleset2_harmony','CRISPRedict_harmony','hyena_score']

result = xgb_model.predict(test_data[features].values)
test_data['DeepDC_score'] = result.flatten()
result = test_data.sort_values(by=['DeepDC_score','DeepSpCas9_harmony','Ruleset2_harmony'],ascending=False)
result = result.loc[:,['chr','start','end','seq1','seq2']+features+['DeepDC_score']]
result['DeepDC_score'] = (result['DeepDC_score']-result['DeepDC_score'].min())/(result['DeepDC_score'].max()-result['DeepDC_score'].min())

In [11]:
result.head(n=10)

,chr,start,end,seq1,seq2,DNase,ATAC,H3K27ac,H3K4me3,GC,length,DeepSpCas9_harmony,DeepCRISPR_harmony,Ruleset2_harmony,CRISPRedict_harmony,hyena_score,DeepDC_score
110,chrX,134460071,134460268,CCCACGGCTACCTAGTGAGCCTGCAAACTG,GACTGCTCAGGAGGAGGAAGCCGGTGGCGG,31525.264171,29848.752725,6790.754156,21021.079781,0.786802,197,2.784937,0.644063,3.156235,3.905681,-0.443919,1.000000
106,chrX,134460071,134460268,GACTGCTCAGGAGGAGGAAGCCGGTGGCGG,CCCACGGCTACCTAGTGAGCCTGCAAACTG,31525.264171,29848.752725,6790.754156,21021.079781,0.786802,197,2.804333,0.644063,3.081003,4.013349,-0.443919,0.992623
107,chrX,134460071,134460268,GACTGCTCAGGAGGAGGAAGCCGGTGGCGG,CCCACGGCTACCTAGTGAGCCTGCAAACTG,31525.264171,29848.752725,6790.754156,21021.079781,0.786802,197,2.804333,0.644063,3.081003,4.013349,-0.443919,0.992623
432,chrX,134460087,134460245,GTGGCGGAGCAGAGGAGGAGGCGGAGGCGC,GAGCCTGCAAACTGGTAGGCGCCGGCGTAG,34035.541666,31096.090641,5091.188868,18061.306468,0.791139,158,1.923263,0.602452,3.973784,3.581815,-1.103730,0.990516
433,chrX,134460087,134460245,GTGGCGGAGCAGAGGAGGAGGCGGAGGCGC,GAGCCTGCAAACTGGTAGGCGCCGGCGTAG,34035.541666,31096.090641,5091.188868,18061.306468,0.791139,158,1.923263,0.602452,3.973784,3.581814,-1.103730,0.990516
709,chrX,134460075,134460265,TGCTCAGGAGGAGGAAGCCGGTGGCGGAGC,CGGCTACCTAGTGAGCCTGCAAACTGGTAG,32075.225142,30198.102786,6538.295100,20714.829248,0.789474,190,1.520585,0.594180,3.429885,3.454708,-0.478026,0.988654
710,chrX,134460075,134460265,TGCTCAGGAGGAGGAAGCCGGTGGCGGAGC,CGGCTACCTAGTGAGCCTGCAAACTGGTAG,32075.225142,30198.102786,6538.295100,20714.829248,0.789474,190,1.520585,0.594180,3.429885,3.454708,-0.478026,0.988654
930,chrX,134460075,134460275,GCGGGCTGACTGCTCAGGAGGAGGAAGCCG,CGGCTACCTAGTGAGCCTGCAAACTGGTAG,31342.356390,30013.853407,7274.516723,22243.704951,0.780000,200,1.112438,0.564067,3.200999,3.319996,-0.307609,0.946256
931,chrX,134460075,134460275,GCGGGCTGACTGCTCAGGAGGAGGAAGCCG,CGGCTACCTAGTGAGCCTGCAAACTGGTAG,31342.356390,30013.853407,7274.516723,22243.704951,0.780000,200,1.112438,0.564067,3.200999,3.319996,-0.307609,0.946256
943,chrX,134460075,134460275,CGGCTACCTAGTGAGCCTGCAAACTGGTAG,GCGGGCTGACTGCTCAGGAGGAGGAAGCCG,31342.356390,30013.853407,7274.516723,22243.704951,0.780000,200,1.049075,0.564067,3.116846,3.175136,-0.307609,0.903720